#!/usr/bin/python
# coding: utf-8

# Author: LE YUAN
# Date: 2019-12-11

# This python script is to obtain coding sequence and protein sequence for essential genes and non-essential genes


def translate_DNA(seq) :
    table = {
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',                 
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
        'TAC':'Y', 'TAT':'Y', 'TAA':'_', 'TAG':'_',
        'TGC':'C', 'TGT':'C', 'TGA':'_', 'TGG':'W',
    }
    protein =""

    if len(seq)%3 == 0:
       
            for i in range(0, len(seq), 3):
               
                codon = seq[i:i + 3]
                
                protein+= table[codon]

    return protein



def main() :
    seq = "ATGAGTAATTTCATTGAAGTCCAGAGGTCTAATATTCAAGAGATTGGTATTATAGAAGATTCATTATCAAGGAGATTATTAAGAAATCCTTATATATTACCGTCAAACTTACAGCCACGACCAAACATCCTTGTATCAAAAGTAACAAAACCAAATTCAACCAAAAGAATATCGATACTACAACAATATGAATTAGGTTATTTTAAAGATCGATATAATCAAATAATAAAAGGCTTGAATCATTGTCTTACTGACGAGAAGGAGTCATTTTCCAGGACATTAGAATTGATCACTGAGCCAGGTGATGGATTTGAAAAGTTTGATGAGATGATCAATGGCATCTCTCTGAATGACAATATAGTGGAAGATCCAAGAAAGTTGTATTCTAGCTTCAGTTCATTAAACAAGGAATTGAATCCTCAAGATGTGACTTTAAAAATAAATAAGAAAACTGGTAAAGAACAAGAGTTTGTTAAAAGAAAACATTTTTTGAGTTCCATTGCTTCACATTTGAAAAATATAGAGATTAACGATATTTTAGACCTTCATCATTTTCATGATTTGTATGTTAGTAATTTTGGTCCGATTCTGTACATTGAATATTTGTATAAATTCCTGAGTTTCCCCTATACCAACGTCAATGGGTTTTATTCGAAATACTTGACAGAATTGAGTCGGTTTCTAGAGGCTACATTATTAAAGTTGCAACCGTTACTAGACTACAATGCCTTGTTGCAAAATTGGAAAAAAGAGTATGACAATGCTAATGAAGAAAGGAAGTCTAATGGCAATGACGGGGACAAATTGTTTTGCAAAGCATGTAATAAATTATTTTCAAAAGAAACTGTTTACCAATCCCATTTGTCAGGAAAGAAACATAAAAAGAATGCATCTCAACAAAACCCAGACAACTTTGTGTCTTCGTTGCCTTGGTTGGAATATTTCATTGAAAAGTTGTGTCAAGTGTTGGCCCCAGAATTGGAATACACTAGAGCACAAGTTGAGAAATTGTCAAACTTGTCGGAAAGAGAGCTACAACTTGATAGACAGGTGCAACACGATATTGAAAATGAATTTGTTGCCATCAACAACGAATTTGATGACGATGATTTGTCTCAAAATGAACATGGCGATGACGATGATAATGATGACTATTTAGATGACAGCTTTAAGAATTTACCTTTAGGCCCAGATGGAACACCAATCCCATTTTGGCTATACAAGCTACAAGAACTACATAAACAATACAATTGTGAAATTTGCGGTAACATAAGTTACAAAGGTAAAAGTGTGTTTATGAAACATTTCAGTGGATCTAAACATCAATATGGTTTGAAGTGTCTTGGTGTTGATGAGAAGAATATGAAAATGTTTAAAAATATTACCAAAATTGATGAAGCTACTGAATTATGGAAAGTGTTGAGAAAGGAGACCAAATTGAAAGTGACTGAATTGGAAAATTCAGTTGAAGTGGAGGATAAAGAAGGTAATGTTATGTTAGAGAAAGATTATATAGATTTGAAAAAACAAGGGTTATTATAG"
    protein = translate_DNA(seq)
    print(protein)


if __name__ == "__main__" :
    main()

        "protein sequence": "MSNFIEVQRSNIQEIGIIEDSLSRRLLRNPYILPSNLQPRPNILVSKVTKPNSTKRISILQQYELGYFKDRYNQIIKGLNHCLTDEKESFSRTLELITEPGDGFEKFDEMINGISSNDNIVEDPRKLYSSFSSLNKELNPQDVTLKINKKTGKEQEFVKRKHFLSSIASHLKNIEINDIMDLHHFHDLYVSNFGPISYIEYLYKFSSFPYANVNGFYSKYLTELSSFLEATLIKLQPLLDYNALLQNWKKEYDNANEERKSNGNDGDKLFCKACNKLFSKETVYQSHLSGKKHKKNASQQNPDNFVSSLPWLEYFIEKLCQVLAPELEYTRAQVEKLSNLSERELQLDRQVQHNIENEFVAINNEFDDDDLSQNEHGDDDDNDNYLDDSFKNLPLGPDGTPIPFWLYKLQGLHKQYNCEICGNISYKGKSVFMKHFSGSKHQYGLKCLGVDEKNMKMFKNITKIDEATELWKVLRKETKLKVTELENSVEVEDKEGNVMSEKDYIDLKKQGLL"
                             MSNFIEVQRSNIQEIGIIEDSLSRRLLRNPYILPSNLQPRPNILVSKVTKPNSTKRISILQQYELGYFKDRYNQIIKGLNHCLTDEKESFSRTLELITEPGDGFEKFDEMINGISLNDNIVEDPRKLYSSFSSLNKELNPQDVTLKINKKTGKEQEFVKRKHFLSSIASHLKNIEINDILDLHHFHDLYVSNFGPILYIEYLYKFLSFPYTNVNGFYSKYLTELSRFLEATLLKLQPLLDYNALLQNWKKEYDNANEERKSNGNDGDKLFCKACNKLFSKETVYQSHLSGKKHKKNASQQNPDNFVSSLPWLEYFIEKLCQVLAPELEYTRAQVEKLSNLSERELQLDRQVQHDIENEFVAINNEFDDDDLSQNEHGDDDDNDDYLDDSFKNLPLGPDGTPIPFWLYKLQELHKQYNCEICGNISYKGKSVFMKHFSGSKHQYGLKCLGVDEKNMKMFKNITKIDEATELWKVLRKETKLKVTELENSVEVEDKEGNVMLEKDYIDLKKQGLL_
[Finished in 0.1s]


